/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Haddock' at '2016-06-02 19:45' with Gradle 2.13
 *
 * @author Haddock, @date 2016-06-02 19:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
